class PostsController < ApplicationController
  def index
    #declare instance variable @posts and assign it to a collection
    #of Post objects using all method provided by ActiveRecord
    #all returns a collection of Post objects
    @posts = Post.all
  end

  def show
    #find the post that corresponds to the id in the params that was passed to  show and assign it to @post.
    #Unlike in the index method, in the show method, we populate an instance variable with a single post, rather than a collection of posts.
    @post = Post.find(params[:id])
  end

  def new
    #create an instance variable, @post, and assign it to an empty post returned by Post.new
    @post = Post.new
  end

  #when user clicks save, create method is called.
  #unlike new, create does not have corresponding view
  #works behind the scenes to collect data and update DB. POST action.
  def create
    #call Post.new to create a new instance of Post
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

   #if we successfully save Post to DB, display a success message using flash[:notice]
   #and redirect user to the route generated by @post. Redirecting to @post will direct user to the posts show view
   if @post.save

     #assign value to flash[:notice]. flash hash is a way to pass temporary values between actions
     #any value in flash will be available in next action an deleted
     flash[:notice] = "Post was saved."
     redirect_to @post
   else
     #if not successfully saved to Post to DB, display error message
     #and render new view again
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :new
   end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
     flash[:notice] = "Post was updated."
     redirect_to @post
    else
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    #call destroy on @post.
    #if successful, set a flash msg and redirect the user to the posts index view
    #if destroy fails, redirect user to the show view using render :show
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to posts_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
end
